[package]
name = "af-types"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "^4.1.4", features = ["derive"] }

anyhow.workspace = true
sui-types.workspace = true
sui-sdk.workspace = true
